"""add title and scheduled_at to rooms

Revision ID: 02dedb9a84d9
Revises: 9c1e927a078d
Create Date: 2026-05-15 07:06:04.024324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dedb9a84d9'
down_revision: Union[str, Sequence[str], None] = '9c1e927a078d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('rooms', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'scheduled_at')
    op.drop_column('rooms', 'title')
    # ### end Alembic commands ###
