"""add started_at ended_at participant_count to rooms

Revision ID: 18ad03b711b7
Revises: d416c1c64cb1
Create Date: 2026-05-10 20:23:19.572613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ad03b711b7'
down_revision: Union[str, Sequence[str], None] = 'd416c1c64cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('participant_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'participant_count')
    op.drop_column('rooms', 'ended_at')
    op.drop_column('rooms', 'started_at')
    # ### end Alembic commands ###
