"""add urgency score to tasks

Revision ID: 958caf2d77be
Revises: 9b78d0736bfc
Create Date: 2026-04-26 19:47:59.593221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958caf2d77be'
down_revision: Union[str, Sequence[str], None] = '9b78d0736bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('urgency_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'urgency_score')
    # ### end Alembic commands ###
