"""add transcript to rooms and transcript source to notes

Revision ID: d416c1c64cb1
Revises: a8b906fd980a
Create Date: 2026-05-07 08:02:12.264513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd416c1c64cb1'
down_revision: Union[str, Sequence[str], None] = 'a8b906fd980a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'transcript')
    # ### end Alembic commands ###
